# Generated by Django 2.1.7 on 2019-02-22 17:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenicspots', '0002_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotsComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='评论内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('spots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenicspots.Spots', verbose_name='景区')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '景区评论',
                'verbose_name_plural': '景区评论',
            },
        ),
    ]
