# Generated by Django 2.1.7 on 2019-02-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='check_time',
            field=models.DateField(default='1970-01-01', verbose_name='签到时间'),
        ),
    ]
