# Generated by Django 2.1.7 on 2019-02-21 14:01

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('price', models.FloatField(verbose_name='单价')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('freight', models.IntegerField(default=0, verbose_name='运费')),
                ('origin', models.CharField(max_length=20, verbose_name='产地')),
                ('pro_type', models.CharField(choices=[('ncp', '农产品'), ('sg', '水果'), ('gyp', '工艺品'), ('fsp', '副食品')], default='ncp', max_length=3, verbose_name='分类')),
                ('buyers', models.IntegerField(default=0, verbose_name='购买人数')),
                ('comments', models.IntegerField(default=0, verbose_name='评论人数')),
                ('details', DjangoUeditor.models.UEditorField(default='', verbose_name='商品详情')),
                ('mainimg', models.ImageField(default='', upload_to='product/mainimg/%Y/%m', verbose_name='商品主图')),
                ('remind', models.CharField(blank=True, max_length=20, null=True, verbose_name='提醒')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
    ]
