# Generated by Django 2.1.7 on 2019-02-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(default='', max_length=30, verbose_name='购买商品名称')),
                ('good_num', models.IntegerField(default=1, verbose_name='购买数量')),
                ('good_price', models.FloatField(default=0, verbose_name='单价')),
                ('good_image', models.ImageField(default='', upload_to='', verbose_name='商品主图')),
                ('good_id', models.IntegerField(default=0, verbose_name='商品id')),
                ('order_num', models.CharField(max_length=25, verbose_name='订单号')),
            ],
            options={
                'verbose_name': '用户购买商品信息',
                'verbose_name_plural': '用户购买商品信息',
            },
        ),
    ]
